name: GitHub Snake Game 🐍

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite (UTC)

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o Graphviz (requisito do snk)
        run: sudo apt-get install -y graphviz

      - name: Gerar o arquivo github-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: John-San
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Confirmar arquivos gerados
        run: ls -R dist

      - name: Commit e push do SVG para o branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
