name: GitHub Snake Game 🐍

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # executa todo dia à meia-noite (UTC)

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar o snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: John-San
          outputs: dist/github-snake.svg

      - name: Commit e push do SVG
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
